//ANSWER IS 137846528820
//THIS QUESTION IS MORE LIKELY TO BE A MATHS. THE FORMULA IS C(N,K) , WHERE N IS THE NO, OF ROWS AND K IS THE NUMBER OF COLUMBS
//FOR MORE DETALIS VISIT https://en.wikipedia.org/wiki/Lattice_path <<-- THIS PAGE
